import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LabelRegistryProvider } from "@/app/context/LabelRegistryContext";
import { SiteHeader } from "@/app/components/SiteHeader";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <LabelRegistryProvider>
          <SiteHeader />
          <div className="flex-1">
            {children}
          </div>
        </LabelRegistryProvider>
      </body>
    </html>
  );
}